name: Deploy Angular to GitHub Pages

# Allow manual trigger in Actions tab
on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout your code
      - uses: actions/checkout@v3

      # 2) Setup Node
      - uses: actions/setup-node@v3
        with:
          node-version: '23'       # match your local Node
          cache: 'npm'

      # 3) Install dependencies
      - run: npm ci

      # 4) Build with correct base-href
      - name: Build
        run: |
          npm run build -- \
            --configuration=production \
            --output-path=dist \
            --base-href=/wheelix/

      # 5) Deploy to gh-pages branch
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/browser
          publish_branch: gh-pages
          user_name: github-actions[bot]
          user_email: github-actions[bot]@users.noreply.github.com
